info:
  namespace: hammerfurniture
items:
  school_chair:
    enabled: true
    display_name: display-name-school_chair
    permission: hammerfurniture.chairs.school_chairs.school_chair
    resource:
      material: PAPER
      generate: false
      model_path: iadeco/school_chair
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: false
        small: true
        hitbox:
          length: 2
          width: 2
          height: 1
          length_offset: -1
      furniture_sit:
        sit_height: 0.6
  school_chair_lazy:
    enabled: true
    display_name: display-name-school_chair_lazy
    permission: hammerfurniture.chairs.school_chairs.school_chair_lazy
    resource:
      material: PAPER
      generate: false
      model_path: iadeco/school_chair_lazy
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: false
        small: true
        hitbox:
          length: 2
          width: 2
          height: 1
          length_offset: -1
      furniture_sit:
        sit_height: 0.6
