info:
  namespace: hammerfurniture
items:
  simple_chair:
    enabled: true
    display_name: display-name-simple_chair
    permission: hammerfurniture.chairs.simple_chair
    lore:
      - lore-chair
    resource:
      material: PAPER
      generate: false
      model_path: iadeco/simple_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
