info:
  namespace: hammerfurniture
items:
  white_chair:
    enabled: true
    display_name: display-name-white_chair
    permission: hammerfurniture.chairs.white_chair
    lore:
      - lore-chair
    resource:
      material: PAPER
      generate: false
      model_path: iadeco/white_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
