info:
  namespace: hammerfurniture
items:
  shrine_of_hammer:
    display_name: "&e锤子神龛"
    lore:
      - "&fꀶ\uF801 &7供奉着锤子。"
    resource:
      material: "PAPER"
      generate: false
      model_path: hammer/shrine_of_hammer
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: true
        solid: true
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true