info:
  namespace: chinesestyle
recipes:
  crafting_table: 
    bamboo_slips: 
      enabled: true
      pattern:
        - XXX 
        - BBB
        - SSS
      pattern_2: 
        - BBB
        - SSS
        - XXX
      ingredients:
        S: STRING
        B: BAMBOO
      result: 
        item: chinesestyle:bamboo_slips 
        amount: 1
    bronze_mirror:
      enabled: true
      pattern:
      - XSX
      - SBS
      - XSX
      ingredients:
        S: STICK
        B: COPPER_INGOT
      result:
        item: chinesestyle:bronze_mirror
        amount: 1
    blue_and_white_porcelain_bowl:
      enabled: true
      pattern:
      - XXX
      - XBX
      - QMQ
      pattern_2:
      - XBX
      - QMQ
      - XXX
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
      result:
        item: chinesestyle:blue_and_white_porcelain_bowl
        amount: 1
    blue_and_white_porcelain_pot:
      enabled: true
      pattern:
      - XPX
      - QBQ
      - MMM
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
        P: PAPER
      result:
        item: chinesestyle:blue_and_white_porcelain_pot
        amount: 1
    blue_and_white_porcelain_vase:
      enabled: true
      pattern:
      - QXQ
      - MBM
      - MMM
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
      result:
        item: chinesestyle:blue_and_white_porcelain_vase
        amount: 1
    blue_and_white_porcelain_pot_1:
      enabled: true
      pattern:
      - XBX
      - QBQ
      - MMM
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
      result:
        item: chinesestyle:blue_and_white_porcelain_pot_1
        amount: 1
  cooking: 
    blue_brick:
      enabled: true
      ingredient: 
        item: BRICKS 
      machines:
      - FURNACE 
      exp: 3 
      cook_time: 200 
      result: 
        item: chinesestyle:blue_brick
        amount: 1
