info:
  namespace: "hammerfurniture"
recipes:
  crafting_table:
    banc_acacia_gauche:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "ACACIA_PLANKS"
        B: "STICK"
      pattern:
        - "AXX"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_acacia_gauche"
        amount: 1
    banc_acacia_droit:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "ACACIA_PLANKS"
        B: "STICK"
      pattern:
        - "XXA"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_acacia_droit"
        amount: 1       
    banc_birch_gauche:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "BIRCH_PLANKS"
        B: "STICK"
      pattern:
        - "AXX"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_birch_gauche"
        amount: 1
    banc_birch_droit:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "BIRCH_PLANKS"
        B: "STICK"
      pattern:
        - "XXA"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_birch_droit"
        amount: 1 
    banc_crimson_gauche:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "CRIMSON_PLANKS"
        B: "STICK"
      pattern:
        - "AXX"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_crimson_gauche"
        amount: 1
    banc_crimson_droit:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "CRIMSON_PLANKS"
        B: "STICK"
      pattern:
        - "XXA"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_crimson_droit"
        amount: 1  
    banc_darkoak_gauche:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "DARK_OAK_PLANKS"
        B: "STICK"
      pattern:
        - "AXX"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_darkoak_gauche"
        amount: 1
    banc_darkoak_droit:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "DARK_OAK_PLANKS"
        B: "STICK"
      pattern:
        - "XXA"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_darkoak_droit"
        amount: 1
    banc_jungle_gauche:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "JUNGLE_PLANKS"
        B: "STICK"
      pattern:
        - "AXX"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_jungle_gauche"
        amount: 1
    banc_jungle_droit:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "JUNGLE_PLANKS"
        B: "STICK"
      pattern:
        - "XXA"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_jungle_droit"
        amount: 1 
    banc_oak_gauche:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "OAK_PLANKS"
        B: "STICK"
      pattern:
        - "AXX"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_oak_gauche"
        amount: 1
    banc_oak_droit:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "OAK_PLANKS"
        B: "STICK"
      pattern:
        - "XXA"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_oak_droit"
        amount: 1   
    banc_spruce_gauche:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "SPRUCE_PLANKS"
        B: "STICK"
      pattern:
        - "AXX"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_spruce_gauche"
        amount: 1
    banc_spruce_droit:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "SPRUCE_PLANKS"
        B: "STICK"
      pattern:
        - "XXA"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_spruce_droit"
        amount: 1   
    banc_warped_gauche:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "WARPED_PLANKS"
        B: "STICK"
      pattern:
        - "AXX"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_warped_gauche"
        amount: 1
    banc_warped_droit:
      permission: itemsadder.hammerfurniture    
      enabled: true
      ingredients:
        A: "WARPED_PLANKS"
        B: "STICK"
      pattern:
        - "XXA"
        - "AAA"
        - "BXB"
      result:
        item: "hammerfurniture:banc_warped_droit"
        amount: 1 
        
items:
  banc_acacia_gauche:
    display_name: "金合欢木长椅（左）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_acacia_gauche"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_acacia_droit:
    display_name: "金合欢木长椅（右）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_acacia_droit"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_birch_gauche:
    display_name: "白桦木长椅（左）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_birch_gauche"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_birch_droit:
    display_name: "白桦木长椅（右）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_birch_droit"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_crimson_gauche:
    display_name: "绯红木长椅（左）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_crimson_gauche"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_crimson_droit:
    display_name: "绯红木长椅（右）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_crimson_droit"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8    
  banc_darkoak_gauche:
    display_name: "深色橡木长椅（左）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_darkoak_gauche"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_darkoak_droit:
    display_name: "深色橡木长椅（右）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_darkoak_droit"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8     
  banc_jungle_gauche:
    display_name: "丛林木长椅（左）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_jungle_gauche"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_jungle_droit:
    display_name: "丛林木长椅（右）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_jungle_droit"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_oak_gauche:
    display_name: "橡木长椅（左）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_oak_gauche"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_oak_droit:
    display_name: "橡木长椅（右）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_oak_droit"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8          
  banc_spruce_gauche:
    display_name: "云杉木长椅（左）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_spruce_gauche"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_spruce_droit:
    display_name: "云杉木长椅（右）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_spruce_droit"
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8   
  banc_warped_gauche:
    display_name: "诡异木长椅（左）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_warped_gauche"
    behaviours:
      furniture:
        fixed_rotation: true
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8
  banc_warped_droit:
    display_name: "诡异木长椅（右）"
    permission: itemsadder.hammerfurniture
    lore:
      - "&7园艺系列"
    resource:
      material: "PAPER"
      generate: false
      model_path: "gardenplus/bancs/banc_warped_droit"
    behaviours:
      furniture:
        fixed_rotation: true
        solid: false
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.8 
