info:
  namespace: hammerfurniture
items:
  small_fountain:
    enabled: true
    display_name: display-name-small_fountain
    permission: hammerfurniture.decorations.small_fountain
    resource:
      material: PAPER
      generate: false
      model_path: iadeco/small_fountain
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: false
        small: true
        solid: true
