info:
  namespace: hammerfurniture
items:
  table:
    enabled: true
    display_name: display-name-table
    permission: hammerfurniture.decorations.table
    lore:
      - lore-decorative-item
    resource:
      material: PAPER
      generate: false
      model_path: iadeco/table
    behaviours:
      furniture:
        small: true
        solid: true
